version: '3.3'

volumes:
  pg_data:
  static:

services:

  db:
    image: postgres:13.10
#    ports:
#      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static:/backend_static  # Или /app/backend_static

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80" # или 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../frontend/build:/usr/share/nginx/html/
#      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
    depends_on:
      - backend
      - frontend
      - db
